### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by ghost** [InfinityRaider/InfinityLib#24] opened 2017-05-10 02:53 UTC
The game crashed whilst rendering ingredient
The game crashed whilst rendering ingredient
Error: java.lang.NoSuchMethodError: com.infinityraider.infinitylib.render.tessellation.ITessellator.translate(DDD)Lcom/infinityraider/infinitylib/render/tessellation/ITessellator;

**Comment by zackeezy** [comment] 2017-07-24 01:32
I had the same crash. crash log: https://pastebin.com/xQgh6wqJ

**Comment by InfinityRaider** [comment] 2017-07-24 02:26
@zackeezy try without optifine

@Galland262 can you give a full crash report please?

**Comment by zackeezy** [comment] 2017-07-24 02:51
@InfinityRaider it crashed again https://pastebin.com/HK67k92L

**Comment by InfinityRaider** [comment] 2017-07-24 13:04
I need the full log.
Also if possible, remove half of your mods (not JEI), if the crash still happens, remove half of them again. If the crash does not happen anymore, put in the half you took out and repeat.

I need to know what mod causes this strange behaviour...

**Comment by zackeezy** [comment] 2017-07-24 19:10
crash log: https://pastebin.com/6Ne3dSRa
latest.log: https://pastebin.com/L9wGZET9
fml-client-latest.log: https://github.com/zackeezy/RandomStuff/blob/master/fml-client-latest.log

The problem is JourneyMaps.

**Comment by Renadarain** [comment] 2018-06-08 17:10
Hi :)

I'm posting this here because I think I have the same crash. It appears to be (in my case) codechickenlib that is causing the crash. Have also tried with and without Optifine.

https://pastebin.com/X4rUFCwA

MC: 1.12.2
Forge: 1.12.2-14.23.4.2707
infinitylib-1.12.0
agricraft-2.12.0-1.12.0-a4

Hope this helps track down the bug :)

Regards,
Renada

**Comment by ProsperCraft** [comment] 2018-09-28 19:57
Client crashing - 

I got this first when searching JEI when in the Ancient Warfare 2 warehouse crafting station.

Now I get it every time I open my inventory.
https://paste.dimdev.org/itezisirus.mccrash
https://paste.dimdev.org/ejuterujeg.mccrash

Now without the warehouse crafting station-
https://paste.dimdev.org/kamokuduva.mccrash

infinitylib-1.12.0
AgriCraft-2.12.0-1.12.0-a6
forge-1.12.2-14.23.4.2760-universal
ancientwarfare-1.12.2-2.6.1.390

Modpack - [Ancient TownCraft](https://minecraft.curseforge.com/projects/ancient-towncraft)

**Comment by ProsperCraft** [comment] 2018-09-28 21:43
Changing to a different computer so my jei wasn't trying to render the same thing allowed me to log back in.

**Comment by ProsperCraft** [comment] 2018-09-29 03:01
I just had it happen again when searching JEI for alienis thaumcraft aspect.

https://paste.dimdev.org/yegusageza.mccrash

**Comment by InfinityRaider** [comment] 2021-03-16 12:41
Closing since I am moving to 1.16 where this is no longer relevant.

**Closed by InfinityRaider** 2021-03-16 12:41 UTC
