### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by Tamaized** [InfinityRaider/InfinityLib#20] opened 2017-03-19 20:19 UTC
Version 0.7.0
Here's all the stacktraces related, popped up one after the other causing MC to hang for a good while before closing.
https://gist.github.com/Tamaized/57aa511e2373e86f4a15af87481a9a90

My guess here is the Tessellator is being messed with in a strange way causing every other block after in JEI to spit out issues with it.

**Comment by InfinityRaider** [comment] 2017-03-20 17:53
This is what happens: our rendering throws an exception, which should normally crash the client, but apparently JEI catches the exception so the game doesnt crash.
Because of this our rendering doesnt finalize the calls to the VertexBuffer, causing every next thing to be rendered to throw exceptions as well (in easier words: "the vertexbuffer still thinks its drawing our tank, so it refuses to draw anything else").

The point is finding out why our tessellator is throwing this exception, it can only tessellate one set of quads at a time, but each thread has its own tessellator, so something weird is going on....

**Comment by Tamaized** [comment] 2017-03-20 18:05
Referencing this as it's most likely related.
https://github.com/InfinityRaider/AgriCraft/issues/777

**Comment by mezz** [comment] 2017-03-28 23:36
Any exception I catch *should* be logged. If you find JEI is hiding an exception somewhere, let me know so I can improve the logging.

**Comment by Scratchman** [comment] 2017-04-03 05:25
We are having the same issue with clients crashing when they are in creative mode and browse JEI or the Creative GUI

browsing with JEI causes this crash.. https://pastebin.com/RsB8RgiB

browsing the creative menu, misc tab .. https://pastebin.com/7zqjEWwC

**Comment by InfinityRaider** [comment] 2017-04-03 16:02
> Any exception I catch should be logged. If you find JEI is hiding an exception somewhere, let me know so I can improve the logging.

I'm not saying JEI hides stacktraces, im saying i dont know why this exception is happening.

**Comment by mezz** [comment] 2017-04-05 06:37
I looked into this a bit more and confirmed what you were saying.

Technical details:
JEI catches and logs the first crash, but the `Tessellator`'s `VertexBuffer` is left in a bad state (it is left with `isDrawing == true`).
I should be able to clear the `VertexBuffer`'s drawing state when I catch a crash. It will not fix the underlying render issue here but it should keep the game from crashing on an unrelated `Tessellator` error.

@Tamaized and @Scratchman, is there a pack I can download that has this issue? Unfortunately I'm not able to reproduce the crash in this report to confirm my fix yet. I tried with just JEI, InfinityLib, and Agricraft but I was unable to reproduce this crash.

**Comment by Tamaized** [comment] 2017-04-05 06:42
We were using a test version of Pure Pack but have removed InfinityLib and Agricraft since. Can find the pack on curse forge and add the two mods and it would be the same as the test version. crashing would happen on searching for "water" or just @agricraft. Should be noted that it crashing was totally random, didn't always do it. No idea why.

Sorry I'd get you the link but it's kinda late here and am on mobile :P

**Comment by mezz** [comment] 2017-04-05 06:42
Thanks, I'll give that a try.

**Comment by mezz** [comment] 2017-04-05 07:00
It looks like the root cause of this issue is extremely similar to the JEI problem and is happening between AE2 and Agricraft:
```
[23:54:22] [Client thread/WARN] [AE2:C]: Unable to get facade sprite for blockstate agricraft:water_pad_normal. Supressing further warnings for this block.
[23:54:22] [Client thread/ERROR] [JEI]: Rendering ingredient crashed: 1xtile.agricraft:water_tank@0 agricraft:water_tank nbt:{agri_material_meta:12,agri_material:"forestry:planks.fireproof.1"}
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:103) ~[TessellatorBakedQuad.class:?]
```
Based on the log, my best guess is that AE2 catches a crash while trying to get a facade sprite for an `agricraft:water_pad_normal` which leaves the InfinityLib `TessellatorBakedQuad` in a bad state. There is no way for it to recover from this automatically, you'll have to look at AE2 to see why it crashed so you can prevent the crash from happening.

**Comment by mezz** [comment] 2017-04-05 07:34
Since it's impossible to catch render errors and fix the state of everything (`VertexBuffer`, `TessellatorBakedQuad`, etc) I'm just going to have JEI crash immediately instead of catching and logging the error. This will give more useful error messages and prevent getting the game into a strange state.

**Comment by InfinityRaider** [comment] 2017-04-05 16:12
Thanks for the digging @mezz

**Comment by Scratchman** [comment] 2017-04-06 06:03
i'm currently putting together a new modpack for a 1.10 server, it's only a test pack at the moment, but you can download the pack here, [TestPack](http://files.mcupdater.com/imaginescape.tk/1.10/TestPack_1.10.2_0403.zip), but you'll need to add the [lantern mod](https://mods.curse.com/mc-mods/minecraft/lantern-mod) back in.. that was the mod that was causing the crashes for us.

**Comment by xAlicatt** [comment] 2017-07-11 06:13
Has this never been fixed? I'm getting this error when trying to scroll through agricraft pages on JEI. 

[https://gist.github.com/xAlicatt/53e090fadbb040356861f45b31c84bc5](url)

**Comment by MSandro** [comment] 2017-07-23 19:43
I also heave this crash when I scroll through JEI or the Creative Tabs!
Please fix!

**Comment by InfinityRaider** [comment] 2017-07-24 02:25
Does any of you have Optifine installed?

**Comment by ParkerRS** [comment] 2017-07-25 20:40
Just to add, I'm having this exact issue as well, and do not have optifine installed. I also ran into a **possibly** related issue where the world flickers rapidly. That issue is also associated with optifine, but again, I do not have it installed. That issue is not reproducible to my knowledge.

**Comment by dragonpc75** [comment] 2017-07-29 23:50
Having this crash issue
https://pastebin.com/sJbdXLWZ
seems related to this thread.

**Comment by Redhandjane** [comment] 2017-08-07 03:12
I'm also having this issue. I crash while scrolling through the items list (to the right) while in my inventory (survival mode). Hopefully this can help you track down the issue, since I know you are aware of it, but more data is good right? :)

https://pastebin.com/yMrvVB1p

**Comment by DrMeteorite117** [comment] 2017-08-09 17:45
IT IS NOT JEI
 
I just figured it out.

I looked at all of the reports and every pack that crashed was using Journey Map.
So, I isolated Agricrat, InfinityLib, and Journey Map.
The crash still occurs if you try to view the Agricraft page of the Creative Mode GUI.
Get the whole story here: [https://pastebin.com/cx3UdmJ6](url)

I assume everyone was using the latest Beta version, like me. Based on how recently this has come up and when the JM Beta was released.
Went back a to the last recommended build of Journey Map and there is no problem so far.
I have submitted a report to [TechBrew](https://minecraft.curseforge.com/members/techbrew).
Anyone else feel free to do the same. The more reports the better.

**Comment by Scratchman** [comment] 2017-08-15 06:50
It's not agricraft. When i had the crash i had Infinitylib and the BoatLantern mod installed. Agricraft for 1.10.2 hadn;t been released yet when i experienced the crash, and it any of the alpha versions of agricraft weren't installed in the pack, The crash stopped when i removed Infinutylib and the boatlantern mod.

I still think it's something between infinitylib and JEI.

**Comment by Redhandjane** [comment] 2017-08-15 15:03
@DrMeteorite117 Thank you! I downgraded Journey Map and I am no longer crashing while trying to scroll through recipes.

**Comment by Geethebluesky** [comment] 2018-05-30 19:36
I'm not using Journeymap and have this crash. I do have Voxelmap in my setup though...

[crashlog](https://gist.github.com/Geethebluesky/96dc525a11a170384623e3013e8b2520)

**Comment by AshenGaming** [comment] 2018-05-31 16:11
I am also having reports of this crash too - https://github.com/AshenGaming/potentia-reborn/issues/25

**Comment by Geethebluesky** [comment] 2018-05-31 16:22
@AshenGaming in your case, since you're using journeymap, have you tried the solutions written above?

**Comment by kotoroshinoto** [comment] 2020-05-19 18:46
i'm getting crashes with this message in my pack as well.

https://www.curseforge.com/minecraft/modpacks/immersiverocketrywithmillenaire

i'm not entirely sure whats causing it. I personally add optifine after i pull the modpack from curseforge, but other people report the crash occurring as well who aren't using it.

**Comment by InfinityRaider** [comment] 2021-03-16 12:43
Closing since I am moving to 1.16 where this is no longer relevant.

**Closed by InfinityRaider** 2021-03-16 12:43 UTC
Labels: bug
