### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by knoxhack** [InfinityRaider/InfinityLib#13] opened 2016-12-23 22:35 UTC
Modpack: Project Ultimate

Server: MMD Public Server

Related Links:
https://minecraft.curseforge.com/projects/mmd-project-ultimate
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues

Crash Report:
https://gist.github.com/knoxhack/6e20ce57675af1071109da36d37b8a9a

**Comment by knoxhack** [comment] 2016-12-23 22:35
https://github.com/InfinityRaider/AgriCraft/issues/758

**Comment by InfinityRaider** [comment] 2016-12-23 22:51
Duplicate of #11

**Closed by InfinityRaider** 2016-12-23 22:51 UTC
